// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCNyhcbW5OWzbTxr1o32Jy-6hilBUqshc',
    appId: '1:392102617861:web:8de5c82237720ea2fc4d6c',
    messagingSenderId: '392102617861',
    projectId: 'delipan-app',
    authDomain: 'delipan-app.firebaseapp.com',
    storageBucket: 'delipan-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf0cos_00xh06-eaV2x82ZXDlOkHdWclI',
    appId: '1:392102617861:android:655247296e03e3fbfc4d6c',
    messagingSenderId: '392102617861',
    projectId: 'delipan-app',
    storageBucket: 'delipan-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3WS4nHzySR3OBSKdLiNokHQFmAENYUpU',
    appId: '1:392102617861:ios:637a1fd5d68c5736fc4d6c',
    messagingSenderId: '392102617861',
    projectId: 'delipan-app',
    storageBucket: 'delipan-app.firebasestorage.app',
    iosBundleId: 'com.delipan.delipan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3WS4nHzySR3OBSKdLiNokHQFmAENYUpU',
    appId: '1:392102617861:ios:637a1fd5d68c5736fc4d6c',
    messagingSenderId: '392102617861',
    projectId: 'delipan-app',
    storageBucket: 'delipan-app.firebasestorage.app',
    iosBundleId: 'com.delipan.delipan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCNyhcbW5OWzbTxr1o32Jy-6hilBUqshc',
    appId: '1:392102617861:web:cac960130ddaa352fc4d6c',
    messagingSenderId: '392102617861',
    projectId: 'delipan-app',
    authDomain: 'delipan-app.firebaseapp.com',
    storageBucket: 'delipan-app.firebasestorage.app',
  );
}
